### ISSUE TITLE
Standard deviation computation incorrect?

### ISSUE THREAD

**Issue by zmeggyesi** [gmpassos/statistics#3]
It looks like the standard deviation calculation is not yielding the correct results. Using the test data of `[10, 20, 30]`, the [STD](https://www.calculator.net/standard-deviation-calculator.html?numberinputs=10%2C+20%2C+30&ctype=p&x=108&y=25) comes out to ≈8.16, but the test has a value of ≈21.[...], which looks wrong.

Looking at the code, it seems like the library only computes the square root of the squared sum divided by the number of elements, whereas it should be the square root of the _variance_ of the sample, the sum of the squared differences from the mean value.

**Comment by gmpassos** [comment]
I will release a fix today, I'm already with a fixed version (just adding more tests). Thanks for the report.

The bug is when the computation is "online". In other parts of the code (extensions) where the computation is in the classic form it's ok.

**Comment by gmpassos** [comment]
Fixed and published:
```
statistics: ^1.0.21
```

https://pub.dev/packages/statistics
